version: '3.8'

services:
  app:
    build: .
    container_name: scalculator-app
    ports:
      - "8080:8080"
    environment:
      APP_NAME: ${APP_NAME}
      DB_URL: jdbc:postgresql://${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      HIBERNATE_DIALECT: ${HIBERNATE_DIALECT}
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./target:/app/target
      - ./pom.xml:/app/pom.xml
    networks:
      - scalculator-network
    command: ["mvn", "spring-boot:run"]

  db:
    image: postgres:13
    container_name: scalculator-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: crud_db
      POSTGRES_USER: crud_user
      POSTGRES_PASSWORD: crud_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scalculator-network

volumes:
  postgres_data:

networks:
  scalculator-network:
    driver: bridge
